name: inventory
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

#--------------------Packages---------------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  get: ^4.6.6

  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  shared_preferences: ^2.3.2
  lottie: ^3.1.3
  elegant_notification: ^2.3.0
  cached_network_image: ^3.4.1
  http: ^1.2.2
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  flutter_otp_text_field: ^1.2.0
  badges: ^3.1.2
  audioplayers: ^6.1.0
  flutter_dotenv: ^5.2.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  file_picker: ^8.1.4
  excel: ^4.0.6
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  supabase_flutter: ^2.8.2
  webview_flutter: ^4.13.0
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.0
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - assets/excel/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700